REM 0. Login and select subscription.
az login
az account set --subscription "ME-MngEnvMCAP036409-binyan-1"

REM 1A. New app only: create a sidecar-enabled Linux Web App. Skip if it already exists.
REM IMPORTANT: Do not add --domain-name-scope. Omitting it keeps Secure Unique Default Hostname disabled.
REM Expected hostname: binyan-data-nexus-api.azurewebsites.net (no hash and no regional suffix).
az webapp create --name "binyan-data-nexus-api" --resource-group "web" --plan "ASP-web-a6cc" --sitecontainers-app --tags "SecurityControl=Ignore"

REM 1B. Check mode first. Run convert ONLY when output starts with DOCKER| or COMPOSE|.
REM If output is SITECONTAINERS, skip convert and continue with sitecontainers list/update.
az webapp config show --name "binyan-data-nexus-api" --resource-group "web" --query linuxFxVersion --output tsv
az webapp sitecontainers convert --mode sitecontainers --name "binyan-data-nexus-api" --resource-group "web" --yes

REM 2. Enable the Web App system-assigned identity and copy the principalId output.
az webapp identity assign --name "binyan-data-nexus-api" --resource-group "web" --query principalId --output tsv

REM 3. Copy the ACR resource ID output.
az acr show --name "binyancontainerea" --query id --output tsv

REM 4. Replace the two placeholders with outputs from steps 2 and 3.
az role assignment create --assignee-object-id "3dfb2fae-3819-48a5-ae14-5d5da3f202db" --assignee-principal-type ServicePrincipal --role "AcrPull" --scope "/subscriptions/4714cf53-6250-494e-915b-7889ff9caa2e/resourceGroups/container/providers/Microsoft.ContainerRegistry/registries/binyancontainerea"

REM 5. Inspect containers. If "main" exists use update; otherwise use create.
az webapp sitecontainers list --name "binyan-data-nexus-api" --resource-group "web" --output table

REM 5A. Run only when the main container does not exist.
az webapp sitecontainers create --name "binyan-data-nexus-api" --resource-group "web" --container-name "main" --image "binyancontainerea.azurecr.io/datanexus-api:latest" --target-port 8000 --is-main true --system-assigned-identity true

REM 5B. Existing converted app / future deployments: update its main container.
az webapp sitecontainers update --name "binyan-data-nexus-api" --resource-group "web" --container-name "main" --image "binyancontainerea.azurecr.io/datanexus-api:latest" --target-port 8000 --is-main true --system-assigned-identity true

REM 8. Enable HTTPS and merge/update the requested resource tag.
az webapp update --name "binyan-data-nexus-api" --resource-group "web" --https-only true --set tags.SecurityControl=Ignore

REM 9. Restart and display the URL.
az webapp restart --name "binyan-data-nexus-api" --resource-group "web"
az webapp show --name "binyan-data-nexus-api" --resource-group "web" --query "{defaultHostName:defaultHostName,domainNameScope:autoGeneratedDomainNameLabelScope}" --output table


REM ============================================================================
REM Frontend Web App: binyan-data-nexus
REM Image: binyancontainerea.azurecr.io/datanexus-server:latest
REM IMPORTANT: Do not add --domain-name-scope. Omitting it keeps Secure Unique Default Hostname disabled.
REM Expected hostname: binyan-data-nexus.azurewebsites.net
REM ============================================================================

REM 10A. New app only: create a sidecar-enabled frontend Web App. Skip if it already exists.
az webapp create --name "binyan-data-nexus" --resource-group "web" --plan "ASP-web-a6cc" --sitecontainers-app --tags "SecurityControl=Ignore"

REM 10B. Check mode first. Run convert ONLY when output starts with DOCKER| or COMPOSE|.
REM Current binyan-data-nexus is already SITECONTAINERS, so skip the convert line below.
az webapp config show --name "binyan-data-nexus" --resource-group "web" --query linuxFxVersion --output tsv
az webapp sitecontainers convert --mode sitecontainers --name "binyan-data-nexus" --resource-group "web" --yes

REM 11. Enable its system-assigned identity and copy the principalId output.
az webapp identity assign --name "binyan-data-nexus" --resource-group "web" --query principalId --output tsv

REM 12. Use the ACR resource ID from step 3. Replace the frontend principal ID placeholder.
az role assignment create --assignee-object-id "97154195-ae03-4950-ba17-35a638c31d47" --assignee-principal-type ServicePrincipal --role "AcrPull" --scope "/subscriptions/4714cf53-6250-494e-915b-7889ff9caa2e/resourceGroups/container/providers/Microsoft.ContainerRegistry/registries/binyancontainerea"

REM 13. Inspect containers. If "main" exists use update; otherwise use create.
az webapp sitecontainers list --name "binyan-data-nexus" --resource-group "web" --output table

REM 13A. Run only when the main container does not exist.
az webapp sitecontainers create --name "binyan-data-nexus" --resource-group "web" --container-name "main" --image "binyancontainerea.azurecr.io/datanexus-server:latest" --target-port 8080 --is-main true --system-assigned-identity true

REM 13B. Existing converted app / future deployments: update its main container.
az webapp sitecontainers update --name "binyan-data-nexus" --resource-group "web" --container-name "main" --image "binyancontainerea.azurecr.io/datanexus-server:latest" --target-port 8080 --is-main true --system-assigned-identity true

REM 15. Configure the Python backend URL. Port is defined on the main sitecontainer.
az webapp config appsettings set --name "binyan-data-nexus" --resource-group "web" --settings "BackendAPI__BaseUrl=https://binyan-data-nexus-api.azurewebsites.net/api" "BackendAPI__Version=v1"

REM 16. Enable HTTPS and merge/update the requested resource tag.
az webapp update --name "binyan-data-nexus" --resource-group "web" --https-only true --set tags.SecurityControl=Ignore

REM 17. Restart and verify the frontend hostname and domain scope.
az webapp restart --name "binyan-data-nexus" --resource-group "web"
az webapp show --name "binyan-data-nexus" --resource-group "web" --query "{defaultHostName:defaultHostName,domainNameScope:autoGeneratedDomainNameLabelScope}" --output table
